big update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,3 +1,7 @@
 #!/usr/bin/env bash
-/home/benjae/nix-config/commit-nix
 sudo nixos-rebuild switch
+if [ $? -eq 0 ]; then
+	bash /etc/nixos/commit-nix
+else
+	echo "it failed lollll"
+fi
